name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'apply' }}

    env:
      AWS_REGION: ap-south-1  # Set your AWS region here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Use the environment variable for the region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2  # Update to a compatible Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Download and Install Istio
        run: |
          curl -L https://istio.io/downloadIstio | sh -
          ISTIO_VERSION=$(ls -d istio-*)
          echo "export PATH=\$PATH:$(pwd)/$ISTIO_VERSION/bin" >> $GITHUB_ENV
          echo "Istio version $ISTIO_VERSION installed."

      - name: Verify Istio Installation
        run: |
          source $GITHUB_ENV
          istioctl x precheck

      - name: Install Istio
        run: |
          source $GITHUB_ENV
          istioctl install --set profile=demo -y

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f istio-ingressgateway.yaml
          kubectl apply -f virtual-service.yaml
          kubectl apply -f frontend-deployment.yaml

      - name: Apply ALB Ingress Controller
        run: kubectl apply -f alb-ingress-controller.yaml

  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'destroy' }}

    env:
      AWS_REGION: ap-south-1  # Set your AWS region here

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Use the environment variable for the region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.2  # Update to a compatible Terraform version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
